import Body from "@/components/Body";
import Header from "@/components/Header";
import SearchService from "@/services/SearchService";
import { SearchResultGrouped } from "@/types/SearchResult";
import Head from "next/head";
import { useState } from "react";
import { HashLoader } from "react-spinners";

export default function Home() {
  const [results, setResults] = useState<SearchResultGrouped[]>([]);
  const [query, setQuery] = useState("");
  const [searchedQuery, setSearchedQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const fetchResults = async () => {
    setSearchedQuery(query);
    setLoading(true);
    SearchService.fetchResults(query)
      .then((res) => {
        setResults(res);
      })
      .catch((err) => {
        console.error(err);
      })
      .finally(() => {
        setLoading(false);
      });
  };

  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center">
        <div className="max-w-7xl w-full px-4">
          <Header
            query={query}
            setQuery={(val: string) => setQuery(val)}
            fetchResults={fetchResults}
          />
          {loading && (
            <div className="flex justify-center items-center p-4">
              <HashLoader size={20} color={"#8B5CF6"} />
            </div>
          )}
          <Body
            loading={loading}
            results={results}
            error={error}
            query={searchedQuery}
          />
        </div>
      </div>
    </>
  );
}
